version: '3.8'

services:
  auticuro-server:
    build:
      context: ./auticuro-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - database

  database:
    image: mysql:7.5
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: auticuro
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
